name: Code Coverage

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # 1. Загружаем ваш код
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 2. Устанавливаем lcov
      - name: Install lcov
        run: sudo apt-get install -y lcov

      # 3. Конфигурируем CMake: Включаем тесты и покрытие
      - name: Configure
        run: cmake -B build -DBUILD_TESTS=ON -DCOVERAGE=ON -DCMAKE_CXX_FLAGS="-Wno-error"

      # 4. Собираем проект и тесты
      - name: Build
        run: cmake --build build

      # 5. Запускаем тесты для генерации .gcda файлов
      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure

      # 6. Генерируем итоговый .info файл с помощью lcov
      - name: Generate coverage report
        run: |
          lcov --capture --directory build --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/third-party/*' '*/tests/*' --output-file coverage.info
          lcov --list coverage.info
